# Generated by Django 5.2 on 2025-05-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('slot', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('slot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slot.slot')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'unique_together': {('student_id', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentCoursePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='studentCourse.studentcourse')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'ordering': ['preference_order'],
                'unique_together': {('student_course', 'teacher_id')},
            },
        ),
    ]
