# Generated by Django 5.2 on 2025-05-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendancerecord', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='timetable_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='conducted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_sessions', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_sessions', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='timetable_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'timetable_slot', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('timetable_slot', 'date')},
        ),
    ]
