# Generated by Django 5.2 on 2025-05-14 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableGenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('max_teacher_slots_per_day', models.IntegerField(default=5)),
                ('enable_lunch_breaks', models.BooleanField(default=True)),
                ('enable_lab_consecutive', models.BooleanField(default=True)),
                ('enable_student_conflicts', models.BooleanField(default=True)),
                ('enable_staggered_schedule', models.BooleanField(default=False)),
                ('min_course_instances', models.IntegerField(default=1)),
                ('division_assignment', models.CharField(choices=[('A', 'Division A (8 AM - 3 PM)'), ('B', 'Division B (10 AM - 5 PM)'), ('C', 'Division C (12 PM - 7 PM)')], default='A', max_length=1)),
                ('solver_timeout', models.IntegerField(default=600)),
                ('is_generated', models.BooleanField(default=False)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('generation_log', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timetable_generation_config',
            },
        ),
    ]
