# Generated by Django 5.2 on 2025-05-13 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(default=0, verbose_name='Batch')),
                ('current_semester', models.IntegerField(default=1, verbose_name='Semester')),
                ('year', models.IntegerField(default=0, verbose_name='Year')),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Roll No')),
                ('student_type', models.CharField(choices=[('Mgmt', 'Management'), ('Govt', 'Government')], default='Mgmt', max_length=50, verbose_name='Student Type')),
                ('degree_type', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=50, verbose_name='Degree Type')),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_students', to='department.department')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
