# Generated by Django 5.2 on 2025-05-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=20, verbose_name='Slot Name')),
                ('slot_type', models.CharField(choices=[('A', 'Slot A (8AM - 3PM)'), ('B', 'Slot B (10AM - 5PM)'), ('C', 'Slot C (12PM - 7PM)')], default='A', max_length=1, verbose_name='Slot Type')),
                ('slot_start_time', models.TimeField(verbose_name='Slot Start Time')),
                ('slot_end_time', models.TimeField(verbose_name='Slot End Time')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='slot.slot')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_assignments', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Slot Assignment',
                'verbose_name_plural': 'Teacher Slot Assignments',
                'ordering': ['day_of_week', 'slot__slot_start_time'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'slot', 'day_of_week'), name='unique_teacher_slot_assignment'), models.UniqueConstraint(fields=('teacher', 'day_of_week'), name='one_slot_per_teacher_per_day')],
            },
        ),
    ]
