# Generated by Django 5.2 on 2025-05-13 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100, verbose_name='Department')),
                ('date_established', models.DateField(blank=True, null=True, verbose_name='Est.')),
                ('contact_info', models.CharField(blank=True, max_length=255, verbose_name='Contact Details')),
                ('hod_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_hod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
